name: Deploy to dok8s

on:
  push:
    tags: ['*']


env:
  GIT_REVISION: ${{ github.ref }}
  REGISTRY: registry.barth.tech
  IMAGE_NAME: registry.barth.tech/library/website

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  image:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      #- name: Log into registry
      #  uses: docker/login-action@v2
      #  with:
      #    registry: registry.barth.tech
      #    username: "${{ secrets.DOCKER_USER }}"
      #    password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Log into registry
        run: echo -n '${{ secrets.DOCKER_PASSWORD }}' | docker login $REGISTRY -u '${{ secrets.DOCKER_USER }}' --password-stdin

      - name: Build image
        run: make image

      - name: Push image
        run: make publish

  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: r-bar/dok8s
          #token: "{{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ssh-key: "${{ secrets.DOK8S_SSH_KEY }}"
      - name: Set version
        run: |
          sed -ie '0,/tag:/ s/tag:.*/tag: ${{ github.ref_name }}/' applications/barth-tech/values.yaml
          git config user.name "rbar/barth.tech actions"
          git config user.email "admin@barth.tech"
          git commit -a -m 'Set barth-tech image tag to ${{ github.ref_name }}'
          git push
