name: Deploy to dok8s

on:
  push:
    tags: ['*']

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_ID: registry.barth.tech/library/barth.tech

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  image:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Build image
        run: make image

      - name: Log into registry
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login registry.barth.tech -u '${{ secrets.DOCKER_USER }}' --password-stdin

      - name: Push image
        run: make publish
